const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    inputBackground: 'white',
    textYellow: '#FFF7C6',
    textGray: '#636362',
    background: '#20201F',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    tabBarInactiveColor: '#7A7A7A',
    borderBottomColor: '#00000047',
    theme: {
      white: '#FFFFFF',
      black: '#000000',
      eccLightWhite: '#FAF9F6',
      backgroundWhite: '#FBFBFB',
      textMediumGray: '#d1d1d1',
      textLightGray: '#9C9C9C',
      primaryColor: '#000F6C',
      eccRedColor: '#A51328',
      backgroundTopCurveSection: '#FAF9F6',
      yellow: '#FFF7C6',
      darkYellow: '#FDEEA4',
      switchEnabledColor: '#0099FF',
      backgroundBtnLightGray: '#3333330F',
      backgroundDarkGray: '#20201F',
      textInputBackgroundDark: '#D9D9D940',
      textInputBackgroundLight: '#D9D9D9',
      signupStepDoneBackground: '#697386',
      signupStepInProgressBackground: '#A51328',
      singupStepRemainingBackgroud: '#C1C9D2',
      textColorCardNumber: '#F7F7F7',
      backgroundColorCurrentBalanceContainer: '#252C5D',
      textInputBottomBorderColor: '#00000047',
      placeholderColor: '#7A7A7A',
      errorColor: '#FC5555',
      blurEffectColor: 'rgba(255, 255, 255, 0.9)',
    },
  },
  dark: {
    errorText: '#DC2626',
    text: '#fff',
    background: '#20201F',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
};
